imports:
    - { resource: config.yml }

framework:
    profiler:
        enabled: false # true by default
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE # DEBUG
