# app/config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $rootDir: '%kernel.root_dir%'

    # makes classes in src/App available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # together with the above _defaults, this is needed for Command-classes to work as in Sf 3.4
    AppBundle\:
        resource: '%kernel.project_dir%/src/AppBundle'
        exclude: '%kernel.project_dir%/src/AppBundle/{Entity,Migrations,Tests}'
