imports:
    - { resource: config.yaml }

framework:
    profiler:
        enabled: true # true by default
        only_exceptions: false
        collect_serializer_data: true

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE # DEBUG
