imports:
    - { resource: parameters.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locales: [de, en]
    default_locale: de  # for routing
    fallback_locale: en # for translation
    
framework:
    secret: '%kernel.secret%'
    annotations:
        enabled: false
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation:
        email_validation_mode: 'html5' # Not setting the "framework.validation.email_validation_mode" config option is deprecated. It will default to "html5" in 7.0
    translator:
        fallbacks: ['%fallback_locale%']
        logging: false
    router:
        utf8: true
    php_errors:
        log: true # Not setting the "framework.php_errors.log" config option is deprecated. It will default to "true" in 7.0

    handle_all_throwables: false # Not setting the "framework.handle_all_throwables" config option is deprecated. It will default to "true" in 7.0
    http_method_override: false # Not setting the "framework.http_method_override" config option is deprecated. It will default to "false" in 7.0
    http_client:
        default_options:
            verify_host: false
            verify_peer: false
        scoped_clients:
            # see: https://symfony.com/doc/current/reference/configuration/framework.html#reference-http-client-scoped-clients
            de.client:
                base_uri: 'https://juedische-geschichte-online.net/'
            en.client:
                base_uri: 'https://jewish-history-online.net/'
            dasjuedischehamburg.client:
                base_uri: 'https://dasjuedischehamburg.de/inhalt/'

twig:
    globals:
        slugify: "@cocur_slugify"
        locales: "%locales%"
    exception_controller: null
    strict_variables: "%kernel.debug%"
        
# Doctrine Configuration
doctrine:
    dbal:
        host:     '%database.host%'
        port:     '%database.port%'
        dbname:   '%database.name%'
        user:     '%database.user%'
        password: '%database.password%'
        #driver:  pdo_mysql
        charset:  '%database.charset%' # UTF8
        options:
                1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
        default_table_options:
            charset: '%database.charset%'
            collate: '%database.charset%_unicode_ci'
            engine:  MyISAM             # InnoDB
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        enable_lazy_ghost_objects: true # Not setting "enable_lazy_ghost_objects" to true is deprecated
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                # https://packagist.org/packages/scienta/doctrine-json-functions
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_UNQUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

scssphp:
    assets:
        "css/base.css":
            src: "web/assets/scss/base.scss"
            sourceMap: true
            outputFolder: web
#            importPaths:
#                - "vendor/twbs/bootstrap/scss"
#            variables:
#                primary: '#ff0066'

jms_i18n_routing:
    default_locale: de
    locales: [de, en]
    # strategy: prefix_except_default
    strategy: custom
    hosts:
        de: '%jms_i18n_routing.hosts.de%'
        en: '%jms_i18n_routing.hosts.en%'
    redirect_to_host: true
    
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig
