# app/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $rootDir: '%kernel.project_dir%'

    # makes classes in src/App available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # together with the above _defaults, this is needed for Command-classes to work as in Sf 3.4
    App\:
        resource: '%kernel.project_dir%/src'
        exclude: '%kernel.project_dir%/src/{Entity,Migrations,Tests}'

    App\Menu\Builder:
        arguments: [ "@knp_menu.factory", "@translator.default", "@request_stack", "@router"  ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
